### ISSUE TITLE
Add spacing utility classes

### ISSUE THREAD

**Issue by DamianMullins** [justeat/fozzie#106]
Recently, I've needed to add some spacing between elements but would have needed to create a new component class or modifier to do so, this seemed quite heavy-handed for my use case.

How does everyone feel about adding some utility classes which we can use throughout the HTML in the form of utility classes?

i.e.

```scss
.u-spacingTop {
    margin-top: spacing();
}

.u-spacingRight {
    margin-right: spacing();
}

.u-spacingBottom {
    margin-bottom: spacing();
}

.u-spacingLeft {
    margin-left: spacing();
}
```

With the possiblity of additional spacing sizes i.e.

```scss
.u-spacingTop {
    margin-top: spacing();
}

.u-spacingTopSmall {
    margin-top: spacing(x2);
}

.u-spacingTopMedium {
    margin-top: spacing(x3);
}

.u-spacingTopLarge {
    margin-top: spacing(x4);
}
```
